name: 'LaunchDarkly Flags'
description: 'Evaluate LaunchDarkly flags in your GitHub Action workflow'

author: 'LaunchDarkly'
branding:
  icon: toggle-right
  color: gray-dark

inputs:
  sdk-key:
    description: 'Server-side SDK key for environment.'
    required: true
    default: ''
  flag-keys:
    description: 'The flag keys to evaluate.'
    required: true
    default: ''
  base-uri:
    description: 'The base URI for the LaunchDarkly server. Most users should use the default value.'
    required: false
    default: 'https://app.launchdarkly.com'
  stream-uri:
    description: 'The base URI for the LaunchDarkly streaming server. Most users should use the default value.'
    required: false
    default: 'https://stream.launchdarkly.com'
  events-uri:
    description: 'The base URI for the LaunchDarkly events server. Most users should use the default value.'
    required: false
    default: 'https://events.launchdarkly.com'
  user-key:
    description: 'The key of the user object used in a feature flag evaluation.'
    required: false
    default: 'ld-github-action-flags'

# Outputs are generated dynamically based on the flag-keys you supply
# outputs:
#   YOUR-FLAG-KEY:
#     description: 'The evaluated flag value'
#   YOUR-OTHER-FLAG-KEY
#     description: 'The evaluated flag value'

runs:
  using: 'node16'
  main: 'dist/index.js'
