name: 'LaunchDarkly Flags'
description: 'Evaluate LaunchDarkly flags in your GitHub Action workflow'

author: 'LaunchDarkly'
branding:
  icon: toggle-right
  color: gray-dark

inputs:
  sdk-key:
    description: 'Server-side SDK key for environment.'
    required: true
    default: ''
  flag-keys:
    description: 'The flag keys to evaluate.'
    required: true
    default: ''
  user-key:
    description: 'The key of the user object used in a feature flag evaluation'
    required: false
    default: 'ld-github-action-flags'
  send-events:
    description: 'Whether to send analytics events back to LaunchDarkly'
    required: false
    default: 'true'
  offline:
    description: 'Whether to use the LaunchDarkly SDK in offline mode'
    required: false
    default: 'false'
  base-uri:
    description: 'The base URI for the LaunchDarkly server. Most users should use the default value.'
    required: false
    default: 'https://app.launchdarkly.com'
  stream-uri:
    description: 'The base URI for the LaunchDarkly streaming server. Most users should use the default value.'
    required: false
    default: 'https://stream.launchdarkly.com'
  events-uri:
    description: The base URI for the LaunchDarkly events server. Most users should use the default value.
    required: false
    default: 'https://events.launchdarkly.com'
  proxy-auth:
    description: 'Allows you to specify basic authentication parameters for an optional HTTP proxy. Usually of the form username:password.'
    required: false
  proxy-host:
    description: 'Allows you to specify a host for an optional HTTP proxy. Both the host and port must be specified to enable proxy support.'
    required: false
  proxy-port:
    description: 'Allows you to specify a port for an optional HTTP proxy. Both the host and port must be specified to enable proxy support.'
    required: false
  proxy-scheme:
    description: 'When using an HTTP proxy, specifies whether it is accessed via http or https'
    required: false

# Outputs are generated dynamically based on the flag-keys you supply
# outputs:
#   YOUR-FLAG-KEY:
#     description: 'The evaluated flag value'
#   YOUR-OTHER-FLAG-KEY:
#     description: 'The evaluated flag value'

runs:
  using: 'node16'
  main: 'dist/index.js'
