name: Conditional
on: push
jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate flags
        id: flags
        uses: ./
        with:
          stream-uri: 'https://stream.ld.catamorphic.com'
          events-uri: 'https://events.ld.catamorphic.com'
          base-uri: 'https://app.ld.catamorphic.com'
          sdk-key: ${{ secrets.SDK_KEY }}
          flag-keys: test-boolean-flag
      - name: If true
        if: steps.flags.outputs.test-boolean-flag == 'true'
        run: echo "It's true"
      - name: If false
        if: steps.flags.outputs.test-boolean-flag == 'false'
        run: echo "It's false"
