name: Setting custom user attributes
on: push
jobs:
  custom-attributes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate flags
        id: flags
        uses: ./
        with:
          stream-uri: 'https://stream.ld.catamorphic.com'
          events-uri: 'https://events.ld.catamorphic.com'
          base-uri: 'https://app.ld.catamorphic.com'
          sdk-key: ${{ secrets.SDK_KEY }}
          flags: test-boolean-flag
        env:
          LD_group: beta
      - name: Test output
        if: steps.flags.outputs.test-boolean-flag != 'false'
        run: exit 1
