name: Deploy to environment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate flags
        id: flags
        uses: ./
        with:
          stream-uri: 'https://stream.ld.catamorphic.com'
          events-uri: 'https://events.ld.catamorphic.com'
          base-uri: 'https://app.ld.catamorphic.com'
          sdk-key: ${{ secrets.SDK_KEY }} # configure environment-specific secret
          flag-keys: test-boolean-flag
