name: Test
on: push

jobs:
  eval-flags:
    name: Evaluate LaunchDarkly Flags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate flags
        id: flags
        uses: ./
        with:
          sdk-key: ${{ secrets.SDK_KEY }}
          flag-keys: |
            test-boolean-flag
            test-string-flag
            test-number-flag
            test-json-flag
      - name: Print flag values
        run: |
          echo ${{ steps.flags.outputs.test-boolean-flag }}
          echo ${{ steps.flags.outputs.test-string-flag }}
          echo ${{ steps.flags.outputs.test-number-flag }}
          echo ${{ toJSON(steps.flags.outputs.test-json-flag) }}
      - name: If boolean flag
        if: fromJSON(steps.flags.outputs.test-boolean-flag) == true
        run: echo "It's true"
      - name: If not boolean flag
        if: fromJSON(steps.flags.outputs.test-boolean-flag) == false
        run: echo "It's false"
