name: Test
on: push

jobs:
  eval-flags:
    name: Evaluate LaunchDarkly Flags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'gha-flags'
      - name: test action locally
        id: ld
        uses: ./
      - run: echo ${{ toJSON(steps.ld.outputs) }}
