name: Test
on: push

jobs:
  eval-flags:
    name: Evaluate LaunchDarkly Flags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test action locally
        id: ld
        uses: ./
        with:
          sdk-key: ${{ secrets.SDK_KEY }}
          flag-keys: |
            coderefs-flag-to-find
            jaz-flag-to-find
      - run: echo ${{ toJSON(steps.ld.outputs) }}
