name: Dynamic context key
on: push
jobs:
  dynamic-context-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Evaluate flags
        id: flags
        uses: ./
        with:
          stream-uri: 'https://stream.ld.catamorphic.com'
          events-uri: 'https://events.ld.catamorphic.com'
          base-uri: 'https://app.ld.catamorphic.com'
          sdk-key: ${{ secrets.SDK_KEY }}
          flags: favorite-animal
          context-key: ${{ github.actor }}
      - name: Favorite animal
        if: steps.flags.outputs.favorite-animal != 'idk'
        run: echo "${{ github.actor }}'s favorite animal is a...${{ steps.flags.outputs.favorite-animal }}"
